target-version = "py311"
line-length = 120

[lint]
select = ["F", "I", "UP", "E", "W"]
ignore = ["E501"]

[lint.per-file-ignores]
"api/scrapers/__init__.py" = ["F401"]
"routers/vlr_router.py" = ["N802"]
"tests/*" = ["F401"]
"benchmarks/*" = ["ALL"]
"__init__.py" = ["F401"]
